---
apiVersion: v1
kind: Pod
metadata:
  name: pods-simple-pod
spec:
  containers:
    - command:
        - echo
        - "the test pod has been successfully ran."
      image: busybox
      name: pods-simple-container
